from url_rewriter.handlers.documentation_url import DocumentationURLRewriteRequestHandler
from url_rewriter.handlers.further_info_url import FurtherInfoURLRewriteRequestHandler
from url_rewriter.handlers.specializations import SpecializationsURLRewriteRequestHandler
