from url_rewriter.handlers.documentation import DocumentationRewriteRequestHandler
from url_rewriter.handlers.further_info import FurtherInfoRewriteRequestHandler
from url_rewriter.handlers.specializations import SpecializationsRewriteRequestHandler
